name: "Game Report"
description: "File a game report"
title: "(Placeholder - Issue title will be automatically populated with the information provided below on submit)"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a report.

        <br/>
  #   > Summary
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short summary of this report. Keep it under 100 characters (about the length of this description).
    validations:
      required: true

  # -- GAME INFORMATION --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Game Information

        <br/>
  #   > Name
  - type: input
    id: game_name
    attributes:
      label: Game Name
      description: Enter the full name of the game. Use the exact name from SteamDB (https://steamdb.info/) if possible, including special characters.
    validations:
      required: true
  #   > App ID
  - type: input
    id: app_id
    attributes:
      label: App ID
      description: Enter the SteamDB App ID (https://steamdb.info/) for the game. Leave blank if unavailable.
    validations:
      required: false
  #   > Store
  - type: dropdown
    id: launcher
    attributes:
      label: Launcher
      description: Select the launcher used to install the game. For non-Steam games, specify the store and installation tool (e.g., Lutris, Heroic Games Launcher).
      options:
        - Steam
        - Heroic Games Launcher
        - Lutris
        - Bottles
        - Other
      default: 0
    validations:
      required: true

  # -- PERFORMANCE TARGETS --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Performance Targets

        <br/>
  #   > Target framerate
  - type: dropdown
    id: target_framerate
    attributes:
      label: Target Framerate
      description: Choose the framerate you were aiming for during gameplay.
      options:
        - <30 FPS
        - 30-39 FPS
        - 40-49 FPS
        - 50-59 FPS
        - 60+ FPS
      default: 4
    validations:
      required: true
  #   > Average Battery Power Draw
  - type: dropdown
    id: average_battery_power_draw
    attributes:
      label: Average Battery Power Draw
      description: Open the in-game performance overlay, record the average BATT wattage over a few minutes of gameplay with your settings, and enter only the number (no units).
      options:
        - "Unknown"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"
        - "9"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "18"
        - "19"
        - "20"
        - "21"
        - "22"
        - "23"
        - "24"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
        - "32"
        - "33"
        - "34"
        - "35"
        - "36"
        - "37"
        - "38"
        - "39"
        - "40"
        - "41"
        - "42"
        - "43"
        - "44"
        - "45"
        - "46"
        - "47"
        - "48"
        - "49"
        - "50"
        - "51"
        - "52"
        - "53"
        - "54"
        - "55"
      default: 0
    validations:
      required: false

  # -- HARDWARE CONFIGURATION --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Hardware Configuration

        <br/>
  #   > Device
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which handheld gaming device was used?
      options:
        - Steam Deck LCD (64GB)
        - Steam Deck LCD (256GB/512GB)
        - Steam Deck OLED
        - ROG Ally Z1
        - ROG Ally Z1 Extreme
        - ROG Ally X
        - Legion Go
      default: 1
    validations:
      required: true
  #   > OS Version
  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: "Specify the version of SteamOS you are running. For other Linux distributions (e.g., SteamFork, Nobara, ChimeraOS), provide the distro name and version in the format `<DISTRO>_<VERSION>` (e.g., `ChimeraOS_46-2`). If the distro is a rolling release and does not have a version, just specify the name (e.g., `CachyOS`)."
      value: 3.6.21
    validations:
      required: true
  #   > Undervolt Applied
  - type: input
    id: undervolt_applied
    attributes:
      label: Undervolt Applied
      description: Have you applied any undervolting to your Deck? Specify it in the format CPU/GPU/SOC (e.g., 20/40/20). Leave blank if no undervolting was applied.
    validations:
      required: false

  # -- STEAMOS GAME PROPERTIES --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## SteamOS Game Properties

        <br/>
  #   > Steam Play Compatibility Tool Used
  - type: dropdown
    id: steam_play_compatibility_tool_used
    attributes:
      label: Steam Play Compatibility Tool Used
      description: Which Steam Play compatibility tool was used?
      options:
        - Steam Proton
        - Glorious Eggroll Proton (GE)
        - Luxtorpeda
        - Boxtron
        - Steam Linux Runtime
      default: 0
    validations:
      required: true
  #   > Compatibility Tool Version
  - type: input
    id: compatibility_tool_version
    attributes:
      label: Compatibility Tool Version
      description: What version of the above compatibility tool are you running? Write "default" if using the default Proton provided by Steam.
      value: default
    validations:
      required: true
  #   > Game Resolution
  - type: dropdown
    id: game_resolution
    attributes:
      label: Game Resolution
      description: Did you configure a custom game resolution?
      options:
        - Default
        - Native
        - 3840x2160
        - 2560x1600
        - 2560x1440
        - 2048x1080
        - 1920x1200
        - 1920x1080
        - 1600x1000
        - 1600x900
        - 1280x800
        - 1280x720
        - 1024x768
        - 1024x640
        - 800x600
        - 800x500
        - 640x480
        - 640x400
      default: 0
    validations:
      required: false
  #   > Launch Options
  - type: input
    id: custom_launch_options
    attributes:
      label: Custom Launch Options
      description: Did you apply any custom launch options?
    validations:
      required: false
  #   >

  # -- STEAMOS PERFORMANCE SETTINGS --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## SteamOS Performance Settings

        <br/>
  #   > Frame Limit
  - type: input
    id: frame_limit
    attributes:
      label: Frame Limit
      description: Enter the frame limit value you set (number only, no units). Leave blank if no frame limit was applied.
    validations:
      required: false
  #   > Disable Frame Limit
  - type: dropdown
    id: disable_frame_limit
    attributes:
      label: Disable Frame Limit
      description: Select whether "Disable Frame Limit" is enabled.
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Enable VRR
  - type: dropdown
    id: enable_vrr
    attributes:
      label: Enable VRR
      description: Select whether "Enable VRR" is enabled.
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Allow Tearing
  - type: dropdown
    id: allow_tearing
    attributes:
      label: Allow Tearing
      description: Select whether "Allow Tearing" is enabled.
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Half Rate Shading
  - type: dropdown
    id: half_rate_shading
    attributes:
      label: Half Rate Shading
      description: Select whether "Half Rate Shading" is enabled.
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > TDP Limit
  - type: input
    id: tdp_limit
    attributes:
      label: TDP Limit
      description: Enter the TDP limit value (number only, no units). Leave blank if not set.
    validations:
      required: false
  #   > Manual GPU Clock
  - type: input
    id: manual_gpu_clock
    attributes:
      label: Manual GPU Clock
      description: Enter the manual GPU clock value (number only, no units). Leave blank if not set.
    validations:
      required: false
  #   > Scaling Mode
  - type: dropdown
    id: scaling_mode
    attributes:
      label: Scaling Mode
      description: Select the Scaling Mode.
      options:
        - Auto
        - Integer
        - Fit
        - Stretch
        - Fill
      default: 0
    validations:
      required: false
  #   > Scaling Filter
  - type: dropdown
    id: scaling_filter
    attributes:
      label: Scaling Filter
      description: Select the Scaling Filter.
      options:
        - Linear
        - Pixel
        - FSR
        - NIS
      default: 0
    validations:
      required: false

  # -- IN-GAME SETTINGS --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## In-Game Settings

        <br/>
  - type: markdown
    attributes:
      value: |
        Formatting notes for Display and Graphics settings:
        - Match the in-game format as closely as possible.
        - Use the styling buttons to add **bold** text and unordered lists for each in-game settings option.
        - Alternatively, use markdown for formatting:
            - Separate sections with level 4 headings (`####`).
            - Use bold labels (`**Setting Option Name:**`) for options.
        - If the game lacks "Display" or "Graphics" options, list resolution details under the **Display** section below.
        - If settings aren't separated, include all details under the **Display** section below.

        Example:
        ```
        #### Section
        - **Option1:** enabled
        ```
  #   > Display
  - type: textarea
    id: game_display_settings
    attributes:
      label: Game Display Settings
      description: Use the styling buttons or markdown to format display settings.
    validations:
      required: true
  #   > Graphics
  - type: textarea
    id: game_graphics_settings
    attributes:
      label: Game Graphics Settings
      description: Use the styling buttons or markdown to format graphics settings.
    validations:
      required: false

  # -- ADDITIONAL NOTES --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Additional Notes

        <br/>
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Add any additional notes.
    validations:
      required: false
