name: "Game Report"
description: "File a game report"
title: "(Placeholder - Issue title will be automatically populated with the information provided below on submit)"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a report.

        <br/>
  #   > Summary
  - type: input
    id: summary
    attributes:
      label: Summary
      description: A short summary of this report. Keep it under 100 characters (about the length of this description).
    validations:
      required: true

  # -- GAME INFORMATION --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Game Information

        <br/>
  #   > Name
  - type: input
    id: game_name
    attributes:
      label: Game Name
      description: Name of the game for this report. Please use the full name. Copy/paste the header from SteamDB if possible, and include all special characters.
    validations:
      required: true
  #   > App ID
  - type: input
    id: app_id
    attributes:
      label: App ID
      description: The App ID from SteamDB (https://steamdb.info/). Leave blank if not applicable.
    validations:
      required: false
  #   > Store
  - type: dropdown
    id: launcher
    attributes:
      label: Launcher
      description: The launcher used to install the game. If the game was not installed directly from Steam, specify the store and the tool used for installation (e.g., Lutris, Heroic Games Launcher, etc.).
      options:
        - Steam
        - Heroic Games Launcher
        - Lutris
        - Bottles
        - Other
      default: 0
    validations:
      required: true

  # -- SETUP EXPERIENCE --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Setup Experience

        <br/>
  #   > Device Compatibility
  - type: dropdown
    id: device_compatibility
    attributes:
      label: Device Compatibility
      description: What was your experience with this game's compatibility with your Device?
      options:
        - Verified
        - Playable
        - Unsupported
      default: 0
    validations:
      required: true
  #   > Target framerate
  - type: dropdown
    id: target_framerate
    attributes:
      label: Target Framerate
      description: What framerate were you targeting?
      options:
        - <30 FPS
        - 30-39 FPS
        - 40-49 FPS
        - 50-59 FPS
        - 60+ FPS
      default: 4
    validations:
      required: true

  # -- HARDWARE CONFIGURATION --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Hardware Configuration

        <br/>
  #   > Device
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Which handheld gaming device was used?
      options:
        - Steam Deck LCD (64GB)
        - Steam Deck LCD (256GB/512GB)
        - Steam Deck OLED
        - ROG Ally Z1
        - ROG Ally Z1 Extreme
        - ROG Ally X
        - Legion Go
      default: 1
    validations:
      required: true
  #   > OS Version
  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: "What version of SteamOS are you running? If you are using another Linux distribution (e.g., ChimeraOS, Nobara, Bazzite), include the distro name and version in the format: `<DISTRO>_<VERSION>`, e.g., (`ChimeraOS_46-2`)."
      value: 3.6.20
    validations:
      required: true
  #   > Steam Deck Undervolt
  - type: input
    id: undervolt_applied
    attributes:
      label: Undervolt Applied
      description: Have you applied any undervolting to your Deck? Specify it in the format CPU/GPU/SOC (e.g., 20/40/20). Leave blank if no undervolting was applied.
    validations:
      required: false

  # -- STEAMOS GAME PROPERTIES --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## SteamOS Game Properties

        <br/>
  #   > Steam Play Compatibility Tool Used
  - type: dropdown
    id: steam_play_compatibility_tool_used
    attributes:
      label: Steam Play Compatibility Tool Used
      description: Which Steam Play compatibility tool was used?
      options:
        - Steam Proton
        - Glorious Eggroll Proton (GE)
        - Luxtorpeda
        - Boxtron
      default: 0
    validations:
      required: true
  #   > Compatibility Tool Version
  - type: input
    id: compatibility_tool_version
    attributes:
      label: Compatibility Tool Version
      description: What version of the above compatibility tool are you running? Write "default" if using the default Proton provided by Steam.
    validations:
      required: true
  #   > Game Resolution
  - type: dropdown
    id: game_resolution
    attributes:
      label: Game Resolution
      description: Did you configure a custom game resolution?
      options:
        - Default
        - Native
        - 3840x2160
        - 2560x1600
        - 2560x1440
        - 2048x1080
        - 1920x1200
        - 1920x1080
        - 1600x1000
        - 1600x900
        - 1280x800
        - 1280x720
        - 1024x768
        - 1024x640
        - 800x600
        - 800x500
        - 640x480
        - 640x400
      default: 0
    validations:
      required: false
  #   > Launch Options
  - type: input
    id: custom_launch_options
    attributes:
      label: Custom Launch Options
      description: Did you apply any custom launch options?
    validations:
      required: false
  #   >

  # -- STEAM DECK PERFORMANCE SETTINGS --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Steam Deck Performance Settings

        <br/>
  #   > Frame Limit
  - type: input
    id: frame_limit
    attributes:
      label: Frame Limit
      description: If you applied a frame limit value, what value did you set? Write only the number without any unit of measure. Leave blank if no frame limit was set.
    validations:
      required: false
  #   > Disable Frame Limit
  - type: dropdown
    id: disable_frame_limit
    attributes:
      label: Disable Frame Limit
      description: Did you enable the "Disable Frame Limit" option?
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Enable VRR
  - type: dropdown
    id: enable_vrr
    attributes:
      label: Enable VRR
      description: Did you enable the "Enable VRR" option?
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Allow Tearing
  - type: dropdown
    id: allow_tearing
    attributes:
      label: Allow Tearing
      description: Did you enable the "Allow Tearing" option?
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > Half Rate Shading
  - type: dropdown
    id: half_rate_shading
    attributes:
      label: Half Rate Shading
      description: Did you enable the "Half Rate Shading" option?
      options:
        - "Off"
        - "On"
      default: 0
    validations:
      required: false
  #   > TDP Limit
  - type: input
    id: tdp_limit
    attributes:
      label: TDP Limit
      description: If you applied a TDP limit value, what value did you set? Write only the number without any unit of measure. Leave blank if no TDP limit was set.
    validations:
      required: false
  #   > Manual GPU Clock
  - type: input
    id: manual_gpu_clock
    attributes:
      label: Manual GPU Clock
      description: If you applied a manual GPU clock value, what value did you set? Write only the number without any unit of measure. Leave blank if no manual GPU clock was set.
    validations:
      required: false
  #   > Scaling Mode
  - type: dropdown
    id: scaling_mode
    attributes:
      label: Scaling Mode
      description: Did you set the Scaling Mode?
      options:
        - Auto
        - Integer
        - Fit
        - Stretch
        - Fill
      default: 0
    validations:
      required: false
  #   > Scaling Filter
  - type: dropdown
    id: scaling_filter
    attributes:
      label: Scaling Filter
      description: Did you set the Scaling Filter?
      options:
        - Linear
        - Pixel
        - FSR
        - NIS
      default: 0
    validations:
      required: false

  # -- IN-GAME SETTINGS --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## In-Game Settings

        <br/>
  - type: markdown
    attributes:
      value: |
        Notes on formatting your Display and Graphics settings:
        - Match the format shown in the game as closely as possible.
        - Use markdown for formatting:
          - Separate each section with a level 4 heading (prefix with `####`).
          - List options with bold labels (use double asterisks, e.g., (`**Setting Option Name:**`).
        - If the game doesn't separate "Display" or "Graphics" options, enter the details under the **Display** section below.
        - If no "Display" or "Graphics" settings exist, just add the resolution used under the **Display** section below.

        Example:
        ```
        #### Section
        - **Option1:** enabled
        ```
  #   > Display
  - type: textarea
    id: game_display_settings
    attributes:
      label: Game Display Settings
      description: Use markdown to show the display settings used in game.
    validations:
      required: true
  #   > Graphics
  - type: textarea
    id: game_graphics_settings
    attributes:
      label: Game Graphics Settings
      description: Use markdown to show the graphics settings used in game.
    validations:
      required: false

  # -- ADDITIONAL NOTES --
  - type: markdown
    attributes:
      value: |
        ---
        <br/>
        <br/>

        ## Additional Notes

        <br/>
  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any additional notes about the game.
    validations:
      required: false
