name: Operations

run-name: >-
  trigger_issue_number="${{ github.event.issue.number }}" trigger_action="${{ github.event.action }}" Report Bot Operations

on:
  issue_comment:
    types: [created, deleted]

jobs:
  notify-remote-webhook:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    if: >
      github.event.action == 'created' &&
      !contains(github.event.comment.body, '[ReportBot Managed Comment]')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Send comment details webhook
        working-directory: .github/scripts
        env:
          DV_WEBHOOK_URL: ${{ secrets.DV_WEBHOOK_URL }}
          DV_WEBHOOK_SECRET: ${{ secrets.DV_WEBHOOK_SECRET }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_AUTHOR_ID: ${{ github.event.issue.user.id }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENT_USER_ID: ${{ github.event.comment.user.id }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_CREATED_AT: ${{ github.event.comment.created_at }}
        run: |
          set -eo pipefail
          python3 send_comment_webhook.py

  handle-reportbot-command:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    if: >
      !contains(github.event.comment.body, '[ReportBot Managed Comment]') &&
      github.event.issue.pull_request == null &&
      (
        github.event.action == 'deleted' ||
        contains(github.event.comment.body, '/reportbot') ||
        contains(github.event.comment.body, '/reportBot') ||
        contains(github.event.comment.body, '/Reportbot') ||
        contains(github.event.comment.body, '/ReportBot') ||
        contains(github.event.comment.body, '@/reportbot') ||
        contains(github.event.comment.body, '@/reportBot') ||
        contains(github.event.comment.body, '@/Reportbot') ||
        contains(github.event.comment.body, '@/ReportBot')
      )
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '.github/scripts/package-lock.json'

      - name: 'Install dependencies'
        working-directory: .github/scripts
        run: |
          npm ci

      - name: 'Run ReportBot'
        working-directory: .github/scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_ACTIONS_BOT_USER: DeckSettings-ReportBot
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          COMMENT_ID: ${{ github.event.comment.id }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMENTER: ${{ github.event.comment.user.login }}
          ACTION_TYPE: ${{ github.event.action }}
        run: |
          echo "${COMMENT_ID:?}"
          echo "${COMMENT_BODY:?}"
          echo "${COMMENTER:?}"
          echo "${ACTION_TYPE:?}"
          echo "Link to trigger comment: https://github.com/${REPO_OWNER:?}/${REPO_NAME:?}/issues/${ISSUE_NUMBER:?}#issuecomment-${COMMENT_ID:?}"
          node report-bot.js
