name: "Weekly Game Reports Check"

on:
  schedule:
    # Run weekly on Friday
    - cron: "0 0 * * 5"

jobs:
  weekly-check-report-for-missing-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ".github/scripts/package-lock.json"

      - name: "Install dependencies"
        working-directory: .github/scripts
        run: |
          npm ci

      - name: "Check all open issues for incomplete template"
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            let page = 1;
            let perPage = 50;
            let allIssues = [];
            while (true) {
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
                per_page: perPage,
                page: page,
              });
              if (issues.length === 0) break; // no more issues
              allIssues = allIssues.concat(issues);
              page++;
            }

            // We'll loop through each open issue
            for (const issue of allIssues) {
              // Skip PRs or any issue that doesn't have a body
              if (issue.pull_request) continue;
              if (!issue.body) continue;

              // Run scripts
              console.log("Running: check-report-for-missing-data.js on issue #" + issue.number);
              execSync(
                `GITHUB_TOKEN=${process.env.GITHUB_TOKEN} ISSUE_NUMBER=${issue.number} REPO_OWNER=${context.repo.owner} REPO_NAME=${context.repo.repo} node check-report-for-missing-data.js`,
                { stdio: 'inherit', cwd: '.github/scripts' }
              );

              console.log("Running: update-issue-title.js on issue #" + issue.number);
              execSync(
                `GITHUB_TOKEN=${process.env.GITHUB_TOKEN} ISSUE_NUMBER=${issue.number} REPO_OWNER=${context.repo.owner} REPO_NAME=${context.repo.repo} node update-issue-title.js`,
                { stdio: 'inherit', cwd: '.github/scripts' }
              );

              console.log("Running: update-issue-labels.js on issue #" + issue.number);
              execSync(
                `GITHUB_TOKEN=${process.env.GITHUB_TOKEN} ISSUE_NUMBER=${issue.number} REPO_OWNER=${context.repo.owner} REPO_NAME=${context.repo.repo} node update-issue-labels.js`,
                { stdio: 'inherit', cwd: '.github/scripts' }
              );
            }

            // The job as a whole doesn't need to fail if we found incomplete issues
            // We'll exit successfully after processing them all.
            console.log("Weekly issue check complete.");
