name: "Weekly Game Reports Check"

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  weekly-check-report-for-missing-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ".github/scripts/package-lock.json"

      - name: "Install dependencies"
        working-directory: .github/scripts
        run: |
          npm ci

      - name: "Check all open issues for incomplete template"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            let page = 1;
            let perPage = 50;
            let allIssues = [];
            while (true) {
              const { data: issues } = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "open",
                per_page: perPage,
                page: page,
              });
              if (issues.length === 0) break; // no more issues
              allIssues = allIssues.concat(issues);
              page++;
            }

            // We'll loop through each open issue
            for (const issue of allIssues) {
              // Skip PRs or any issue that doesn't have a body
              if (issue.pull_request) continue;
              if (!issue.body) continue;

              // Run script
              execSync(`GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ISSUE_NUMBER=${issue.number} REPO_OWNER=DeckSettings REPO_NAME=deck-settings node check-report-for-missing-data.js`, { stdio: 'inherit' });

            }

            // The job as a whole doesn't need to fail if we found incomplete issues
            // We'll exit successfully after processing them all.
            console.log("Weekly issue check complete.");
